### ISSUE TITLE
replace LinearLayout with Recyclerview 

### ISSUE THREAD

**Issue by abbasalim** [florent37/AndroidParallax#3]
i want use Recyclerview  in my app. what must i do it?

**Comment by SanthoshDhandapani** [comment]
1) Add   android:fillViewport="true" in the scroll view

2) Change linear layout to recyclerview and declare its height as wrap content

3) Now in java, set the setAutoMeasureEnabled to true in the linear layout manager of recycler view. 
    ( setAutoMeasureEnabled method is supported from support library 23 of recycler view )
